# キャルbotの管理者のID
ADMIN_ID: '420084355105423367'

# キャルが起動時に喋るメッセージと場所
STARTUP:
  MESSAGE: きゃるきゃるーん
  CHANNEL_ID: '732598723376316456'

# ウェルカムメッセージで使うチャンネルのID
WELCOME_CHANNEL:
  CHAT_ID: '714020537231343656'
  POLICY_ID: '720761726391287939'
  INTRODUCTION_ID: '714358491707473950'

# 凸に関するチャンネル
CONVEX_CHANNEL:
  REPORT_ID: '735190970760429648'

# ロールのID
ROLE_ID:
  # リーダーのロール
  LEADER: '722547140487938181'
  # サブリーダーのロール
  SUB_LEADER: '739666967509598218'
  # クランメンバーのロール
  CLAN_MEMBERS: '719906267824521267'
  # 凸残のロール
  REMAIN_CONVEX: '738500598718136373'
  # ヤバイわよ！のロール
  YABAIWAYO: '717003659745165373'

# カスタム絵文字のID
EMOJI_ID:
  # 草野優衣のカスタム絵文字
  YUI_KUSANO: '715020255059247146'
  # 確認のカスタム絵文字
  SAKUJO: '739441861521047592'

# コマンド入力が出来るチャンネル
COMMAND_CHANNEL:
  # 凸予約コマンドが入力出来るチャンネル
  CONVEX_RESERVATION:
    - 凸予約
    - bot-test
  # 管理コマンドが入力できるチャンネル
  MANAGEMENT:
    - 運営管理用
    - bot-test
  PROGRESS:
    - 進行
    - 運営管理用
    - bot-test

# 特定メッセージを入力した際にbotが画像を送信するチャンネル
SEND_IMAGE_CHANNEL:
  - 雑談
  - vc用
  - bot-test

# URL一覧
URL:
  YABAIWAYO: https://raw.githubusercontent.com/beroba/convex-management/master/assets/yabaiwayo_small.png
  SPREADSHEET: https://docs.google.com/spreadsheets/d/11uWCeVC5kWKYAWVJrHRoYz502Wue6qHyDtbNM4UULso

# 凸管理のシート情報
MANAGEMENT_SHEET:
  SHEET_NAME: 凸管理
  MEMBER_CELLS: A3:A32

# 凸予約のシート情報
RESERVATION_SHEET:
  SHEET_NAME: 凸予約

# 情報のシート情報
INFORMATION_SHEET:
  SHEET_NAME: 情報
  MEMBER_CELLS: A3:A32
  DATE_CELLS: C3:E7
  BOSS_CELLS: G3:H7
  CURRENT_CELLS: J3:K3

