# キャルが起動時に喋るメッセージと場所
STARTUP:
  MESSAGE: きゃるきゃるーん
  CHANNEL_ID: '732598723376316456'

# ウェルカムメッセージで使うチャンネルのID
WELCOME_CHANNEL:
  CHAT_ID: '714020537231343656'
  POLICY_ID: '720761726391287939'
  INTRODUCTION_ID: '714358491707473950'

# 凸に関するチャンネル
CONVEX_CHANNEL:
  REPORT_ID: '735190970760429648'

# ロールのID
ROLE_ID:
  # クランメンバーのロール
  CLAN_MEMBERS: '719906267824521267'
  # 凸残のロール
  REMAIN_CONVEX: '738500598718136373'

# カスタム絵文字のID
EMOJI_ID:
  # 草野優衣のカスタム絵文字
  YUI_KUSANO: '715020255059247146'
  # 確認のカスタム絵文字
  KAKUNIN: '714684451057041448'

# コマンド入力が出来るチャンネル
COMMAND_CHANNEL:
  # 凸予約コマンドが入力出来るチャンネル
  CONVEX_RESERVATION:
    - 凸予約
    - bot-test
  # 管理コマンドが入力できるチャンネル
  MANAGEMENT:
    - 運営管理用
    - bot-test
  PROGRESS:
    - 進行
    - bot-test

# 特定メッセージを入力した際にbotが画像を送信するチャンネル
SEND_IMAGE_CHANNEL:
  - 雑談
  - vc用
  - bot-test

# 画像のURL
URL:
  YABAIWAYO: https://raw.githubusercontent.com/beroba/convex-management/master/assets/yabaiwayo_small.png

# 凸管理のシート情報
MANAGEMENT_SHEET:
  SHEET_NAME: 凸管理
  MEMBER_CELLS: A2:A31

# 凸予約のシート情報
RESERVATION_SHEET:
  SHEET_NAME: 凸予約

# 情報のシート情報
INFORMATION_SHEET:
  SHEET_NAME: 情報
  DATE_CELLS: B2:C6
  BOSS_CELLS: E2:F6

