# キャルが起動時に喋るメッセージと場所
STARTUP:
  MESSAGE: きゃるきゃるーん
  CHANNEL_ID: '732598723376316456'

# ウェルカムメッセージで使うチャンネルのID
WELCOME_CHANNEL:
  CHAT_ID: '714020537231343656'
  POLICY_ID: '720761726391287939'
  INTRODUCTION_ID: '714358491707473950'

# ロールのID
ROLE_ID:
  # クランメンバーのID
  CLAN_MEMBERS: '719906267824521267'

# コマンド入力が出来るチャンネル
COMMAND_CHANNEL:
  # 凸予約コマンドが入力出来るチャンネル
  CONVEX_RESERVATION:
    - 凸予約
    - bot-test
  # 管理コマンドが入力できるチャンネル
  MANAGEMENT:
    - 運営管理用
    - bot-test
  PROGRESS:
    - 進行
    - bot-test

# 特定メッセージを入力した際にbotが画像を送信するチャンネル
SEND_IMAGE_CHANNEL:
  - 雑談
  - vc用
  - bot-test

# 画像のURL
URL:
  YABAIWAYO: https://raw.githubusercontent.com/beroba/convex-management/master/assets/yabaiwayo.png

# 凸管理用のワークシート名
CONVEX_WORKSHEET:
  MANAGEMENT: 凸管理
