# キャルが起動時に喋るメッセージ
STARTUP_MESSAGE: きゃるきゃるーん

# 特定メッセージを入力した際にbotが画像を送信するチャンネル
SEND_IMAGE_CHANNEL:
  - 雑談
  - vc用
  - bot-test

# 画像のURL
URL:
  YABAIWAYO: https://raw.githubusercontent.com/beroba/convex-management/master/assets/yabaiwayo.png

# ホワイトリストのシート名とセルの範囲
WHITE_LIST:
  SHEET: 凸管理
  CELLS: A2:A100
