# キャルbotの管理者のID
ADMIN_ID: '420084355105423367'

# チャンネルのID
CHANNEL_ID:
  # botの通知用のチャンネル
  BOT_NOTIFY: '732598723376316456'
  # 雑談のチャンネル
  CHAT: '714020537231343656'
  # チャンネル案内のチャンネル
  CHANNEL_POLICY: '720761726391287939'
  # 自己紹介のチャンネル
  INTRODUCTION: '714358491707473950'
  # 凸報告のチャンネル
  CONVEX_REPORT: '735190970760429648'
  # 凸予定のチャンネル
  CONVEX_RESERVATE: '720767289070321764'
  # 凸状況のチャンネル
  CONVEX_SITUATION: '762328019012157460'
  # 凸状況履歴のチャンネル
  CONVEX_HISTORY: '735186004238925824'
  # 持ち越し状況のチャンネル
  CARRYOVER_SITUATION: '739400220290449488'
  # 進行のチャンネル
  PROGRESS: '720773327395881130'
  # 持ち越し凸先チャンネル
  CARRYOVER_DESTINATION: '761073612261818378'
  # idスクショ送信のロールを付与するチャンネル
  PLAYER_ID_ROLE_GRANT: '746783106555445349'
  # プレイヤーIDのスクショを送信するチャンネル
  PLAYER_ID_SEND: '745817773552304159'
  # プレイヤーIDのスクショを保存しておくチャンネル
  PLAYER_ID_LIST: '743312873195044864'

# カスタム絵文字のID
EMOJI_ID:
  # 草野優衣のカスタム絵文字
  YUI_KUSANO: '715020255059247146'
  # 取消のカスタム絵文字
  TORIKESHI: '749671174824263731'
  # 完了のカスタム絵文字
  KANRYOU: '749671129345425489'
  # ルナのカスタム絵文字
  RUNA: '732785034968301718'
  # まざらしのカスタム絵文字
  MAZARASHI: '782668872435367987'
  # レジギガスのカスタム絵文字
  USAMARU: '784071995758870550'
  # 抹茶ですよのカスタム絵文字
  MACCHA_DESUYO: '739681535967363082'
  # 肉のカスタム絵文字
  NIKU: '781580398546780203'

# ロールのID
ROLE_ID:
  # リーダーのロール
  LEADER: &LEADER '722547140487938181'
  # サブリーダーのロール
  SUB_LEADER: &SUB_LEADER '739666967509598218'
  # 進行役のロール
  PROGRESS: '714033569604829284'
  # クランメンバーのロール
  CLAN_MEMBERS: '719906267824521267'
  # 妹クランメンバーのロール
  SISTER_MEMBERS: '761034768388718624'
  # 凸残のロール
  REMAIN_CONVEX: '738500598718136373'
  # タスキルのロール
  TASK_KILL: '779684047337160726'
  # ともだちのロール
  TOMODACHI: '750507399672234004'
  # idスクショ送信のロール
  PLAYER_ID_SEND: '746782741210595378'
  # ヤバイわよ！のロール
  YABAIWAYO: '717003659745165373'

# クラバトコマンドの実行可能ユーザー
COMMAND_ROLE:
  - *LEADER
  - *SUB_LEADER

# ボスのロールID
BOSS_ROLE_ID:
  a: '756495147646058498'
  b: '756091369839263825'
  c: '756495323874066472'
  d: '756495357340286977'
  e: '756495432535769108'

# 段階のロールID
STAGE_ROLE_ID:
  first: '788236122823720980'
  second: '788236161503330315'
  third: '788236205967802419'
  fourth: '788236243183861760'
  fifth: '791294504124022805'

# 段階毎のHP
STAGE_HP:
  first:
    a: 600
    b: 800
    c: 1000
    d: 1200
    e: 1500
  second:
    a: 600
    b: 800
    c: 1000
    d: 1200
    e: 1500
  third:
    a: 700
    b: 900
    c: 1300
    d: 1500
    e: 2000
  fourth:
    a: 1700
    b: 1800
    c: 2000
    d: 2100
    e: 2300
  fifth:
    a: 8500
    b: 9000
    c: 9500
    d: 10000
    e: 11000

# 凸状況のメッセージID
CONVEX_MESSAGE_ID:
  SITUATION: '762861794803843073'
  PLAN: '762861796217716817'

# コマンド入力が出来るチャンネル
COMMAND_CHANNEL:
  # クラバトコマンドが入力できるチャンネル
  CLAN_BATTLE:
    - 進行
    - bot-test
  # 凸予定コマンドが入力できるチャンネル
  CONVEX_RESERVATION:
    - 凸予定
    - bot-test
  # 管理コマンドが入力できるチャンネル
  MANAGEMENT:
    - 運営管理用
    - bot-test

# 特定メッセージを入力した際にbotがあれこれするチャンネル
THIS_AND_THAT_CHANNEL:
  - 雑談
  - くらばと
  - クラバト雑談
  - vc用
  - vc用-姉
  - bot-test

# 絵文字を押さないチャンネル
NOT_EMOJI_CHANNEL:
  - 凸状況
  - 凸状況履歴

# クラバトカテゴリーの場所
CATEGORY:
  POSITION: 5

# URL一覧
URL:
  YABAIWAYO: https://raw.githubusercontent.com/beroba/convex-management/master/assets/yabaiwayo_small.png
  SPREADSHEET: https://docs.google.com/spreadsheets/d/11uWCeVC5kWKYAWVJrHRoYz502Wue6qHyDtbNM4UULso

# 凸管理のシート情報
MANAGEMENT_SHEET:
  SHEET_NAME: 凸管理
  MEMBER_CELLS: A3:B32

# 凸予定のシート情報
PLAN_SHEET:
  SHEET_NAME: 凸予定
  PERSON_CELLS: B3:B1002
  PLAN_CELLS: A3:H1002

# 情報のシート情報
INFORMATION_SHEET:
  SHEET_NAME: 情報
  MEMBER_CELLS: A3:B32
  DATE_CELLS: D3:F8
  BOSS_CELLS: H3:I7
  CATEGORY_CELLS: O3:P12
  STAGE_CELLS: R3:S7
  CURRENT_CELL: K3,L3,M3
  MEMBER_COLUMN: A
  DATE_COLUMN: E
  CATEGORY_COLUMN: P
  STAGE_COLUMN: S

# 妹クランのシート情報
SISTER_SHEET:
  SHEET_NAME: 妹クラン
  MEMBER_CELLS: A3:B32
  MEMBER_COLUMN: A
