# 段階毎の周回数とHP
STAGE:
  FIRST:
    NUMBER: 1
    LAP: [1, 3]
    HP:
      a: 600
      b: 800
      c: 1000
      d: 1200
      e: 1500
  SECOND:
    NUMBER: 2
    LAP: [4, 10]
    HP:
      a: 600
      b: 800
      c: 1000
      d: 1200
      e: 1500
  THIRD:
    NUMBER: 3
    LAP: [11, 30]
    HP:
      a: 1200
      b: 1400
      c: 1700
      d: 1900
      e: 2200
  FOURTH:
    NUMBER: 4
    LAP: [31, 38]
    HP:
      a: 2200
      b: 2300
      c: 2700
      d: 2900
      e: 3100
  FIFTH:
    NUMBER: 5
    LAP: [39]
    HP:
      a: 10500
      b: 11000
      c: 12500
      d: 14000
      e: 15000

# bot操作のメッセージID
BOT_OPERATION:
  CONVEX_SITUATION: '885842181569536020'
  TIME_LIMIT: '885850652448788491'
  ATTENDANCE: '885865380625678387'
  TASK_KILL: '885856546578374718'

# ダメージ集計のフラグ
DAMAGE_FLAG:
  ok: '  ⭕ '
  ng: '  🆖 '
  check: '  ✅ '
  none: 'ㅤㅤㅤ'
