# 活動時間のシート情報
ACTIVITY_TIME_SHEET:
  SHEET_NAME: 活動時間
  SEPARATE: [D, G, K, M, Q, U, 'Y']

# 凸管理のシート情報
MANAGEMENT_SHEET:
  SHEET_NAME: 凸管理

# 情報のシート情報
INFORMATION_SHEET:
  SHEET_NAME: 情報
  MEMBER_CELLS: A3:C32
  DATE_CELLS: E3:G8
  BOSS_CELLS: I3:K7
  LAP_CELL: M3
  LAP_CELLS: N3,O3,P3,Q3,R3
  HP_CELLS: N4,O4,P4,Q4,R4
  MEMBER_COLUMN: A
  LIMIT_COLUMN: C
  DATE_COLUMN: F

# 妹クランのシート情報
SISTER_SHEET:
  SHEET_NAME: 妹クラン
  MEMBER_CELLS: A3:B32
  MEMBER_COLUMN: A
