# 段階毎の周回数とHP
STAGE:
  FIRST:
    NUMBER: 1
    LAP: [1, 3]
    HP:
      a: 600
      b: 800
      c: 1000
      d: 1200
      e: 1500
  SECOND:
    NUMBER: 2
    LAP: [4, 10]
    HP:
      a: 600
      b: 800
      c: 1000
      d: 1200
      e: 1500
  THIRD:
    NUMBER: 3
    LAP: [11, 30]
    HP:
      a: 1200
      b: 1400
      c: 1700
      d: 1900
      e: 2200
  FOURTH:
    NUMBER: 4
    LAP: [31, 40]
    HP:
      a: 1900
      b: 2000
      c: 2300
      d: 2500
      e: 2700
  FIFTH:
    NUMBER: 5
    LAP: [41]
    HP:
      a: 9500
      b: 10000
      c: 11000
      d: 12000
      e: 13000

# クラバトカテゴリーの場所
CATEGORY:
  POSITION: 9

# bot操作のメッセージID
BOT_OPERATION:
  CONVEX_SITUATION: '885842181569536020'
  TIME_LIMIT: '885850652448788491'
  ATTENDANCE: '885865380625678387'
  TASK_KILL: '885856546578374718'
