# 段階毎の周回数とHP
STAGE:
  FIRST:
    NUMBER: 1
    LAP: [1, 3]
    HP:
      a: 600
      b: 800
      c: 1000
      d: 1200
      e: 1500
  SECOND:
    NUMBER: 2
    LAP: [4, 10]
    HP:
      a: 600
      b: 800
      c: 1000
      d: 1200
      e: 1500
  THIRD:
    NUMBER: 3
    LAP: [11, 30]
    HP:
      a: 1200
      b: 1400
      c: 1700
      d: 1900
      e: 2200
  FOURTH:
    NUMBER: 4
    LAP: [31, 40]
    HP:
      a: 1900
      b: 2000
      c: 2300
      d: 2500
      e: 2700
  FIFTH:
    NUMBER: 5
    LAP: [41]
    HP:
      a: 8500
      b: 9000
      c: 9500
      d: 10000
      e: 11000

# クラバトカテゴリーの場所
CATEGORY:
  POSITION: 8
