# チャンネルのID
CHANNEL_ID:
  # botの通知用
  BOT_NOTIFY: '732598723376316456'
  # 雑談
  CHAT: '714020537231343656'
  # チャンネル案内
  CHANNEL_POLICY: '720761726391287939'
  # 自己紹介
  INTRODUCTION: '714358491707473950'

  # クラバト連絡
  CLAN_BATTLE_CONTACT: '749663068832792643'
  # 凸報告
  CONVEX_REPORT: '735190970760429648'
  # 凸予定
  CONVEX_RESERVATE: '720767289070321764'
  # 凸予定一覧
  CONVEX_LIST_RESERVATE: '859451810175909948'
  # 凸状況
  CONVEX_SITUATION: '848602049217953822'
  # 凸状況履歴
  CONVEX_HISTORY: '735186004238925824'
  # 持越状況
  CARRYOVER_SITUATION: '739400220290449488'
  # 進行-連携
  PROGRESS: '720773327395881130'
  # 活動時間
  ACTIVITY_TIME: '795629249754431488'
  # 持越凸先
  CARRYOVER_DESTINATION: '761073612261818378'

  # 肉
  NIKU: '714033825100988438'
  # 性癖調査18禁
  SEIHEKI: '724549820978692166'
  # 性癖調査よろず18禁
  SEIHEKI_YOROZU: '755515505678352535'

  # idスクショ送信のロールを付与用
  PLAYER_ID_ROLE_GRANT: '746783106555445349'
  # プレイヤーIDのスクショを送信用
  PLAYER_ID_SEND: '745817773552304159'
  # プレイヤーIDのスクショを保存用
  PLAYER_ID_LIST: '743312873195044864'

  # さとりんご名言ツイート
  OREUSO: '851180265959063562'
  # tl修正の名前変更一覧
  TL_FORMAT: '856844393621225492'
  # キャルステータス
  CAL_STATUS: '879241877256282164'


# コマンド入力が出来るチャンネル
COMMAND_CHANNEL:
  # クラバトコマンドが入力できるチャンネル
  CLAN_BATTLE:
    - 進行-連携
    - くらばと-vc用
    - おためしキャルちゃん
    - 🔔情報共有🔔
    - bot-test
    - tlを修正するﾈｺﾁｬﾝ
  # 凸予定コマンドが入力できるチャンネル
  CONVEX_RESERVATION:
    - 凸予定
    - bot-test
  # 管理コマンドが入力できるチャンネル
  MANAGEMENT:
    - 運営管理用
    - bot-test

# キャルがどうでも良い機能を実行するチャンネル
MAJOR_THAT_CHANNEL:
  - 雑談
  - 進行-連携
  - 茶室
  - 茶の間
  - 🔔情報共有🔔
  - vc用
  - vc用2
  - vc用-運営
  - くらばと-vc用
  - bot-test
  - しろはの部屋
  - times_smicle
  - おためしキャルちゃん
  - aki
  - ttsチャンネル

# キャルがかなりどうでも良い機能を実行するチャンネル
NETA_THAT_CHANNEL:
  - 雑談
  - 茶室
  - 茶の間
  - vc用
  - vc用2
  - bot-test
  - しろはの部屋
  - times_smicle
  - おためしキャルちゃん

# 絵文字を押さないチャンネル
NOT_EMOJI_CHANNEL:
  - 凸宣言-ボス状況
  - 凸報告
  - 持越状況
  - 凸可能時間
  - 凸予定
  - 凸状況
  - 凸状況履歴