import * as Discord from 'discord.js'

const FLAGS = Discord.Intents.FLAGS

// prettier-ignore
export const Partials: Discord.PartialTypes[] = [
  'USER',
  'CHANNEL',
  'GUILD_MEMBER',
  'MESSAGE',
  'REACTION'
]

export const Intents = [
  FLAGS.GUILDS,
  FLAGS.GUILD_MEMBERS,
  FLAGS.GUILD_BANS,
  FLAGS.GUILD_EMOJIS_AND_STICKERS,
  FLAGS.GUILD_INTEGRATIONS,
  FLAGS.GUILD_WEBHOOKS,
  FLAGS.GUILD_INVITES,
  FLAGS.GUILD_VOICE_STATES,
  FLAGS.GUILD_PRESENCES,
  FLAGS.GUILD_MESSAGES,
  FLAGS.GUILD_MESSAGE_REACTIONS,
  FLAGS.GUILD_MESSAGE_TYPING,
  FLAGS.DIRECT_MESSAGES,
  FLAGS.DIRECT_MESSAGE_REACTIONS,
  FLAGS.DIRECT_MESSAGE_TYPING,
]
